#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<double,16> double16;
typedef hls::vector<double,8> double8;
typedef hls::vector<double,4> double4;
typedef hls::vector<double,2> double2;
typedef hls::vector<double,1> double1;



void kernel_nlp(double C[200][220], double A[200][240], double B[240][220]) {

    int i;
    int j;
    int k;
    for ( i = 0; i < 200; i++) {
        for ( j = 0; j < 220; j++) {
            C[i][j] *= beta;
        }
    }
    for ( i = 0; i < 200; i++) {
        for ( j = 0; j < 220; j++) {
            for ( k = 0; k < 240; k++) {
                C[i][j] += alpha * A[i][k] * B[k][j];
            }
        }
    }
}
