#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<double,16> double16;
typedef hls::vector<double,8> double8;
typedef hls::vector<double,4> double4;
typedef hls::vector<double,2> double2;
typedef hls::vector<double,1> double1;



void kernel_nlp(double A[390][410], double x[410], double y[410], double tmp[390]) {

    int j;
    int i;
    for ( j = 0; j < 410; j++) {
        y[j] = 0.0;
    }
    for ( i = 0; i < 390; i++) {
        tmp[i] = 0.0;
    }
    for ( i = 0; i < 390; i++) {
        for ( j = 0; j < 410; j++) {
            tmp[i] = tmp[i] + A[i][j] * x[j];
        }
    }
    for ( j = 0; j < 410; j++) {
        for ( i = 0; i < 390; i++) {
            y[j] = y[j] + A[i][j] * tmp[i];
        }
    }
}
