#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<float,16> float16;
typedef hls::vector<float,8> float8;
typedef hls::vector<float,4> float4;
typedef hls::vector<float,2> float2;
typedef hls::vector<float,1> float1;



void kernel_nlp(float C[240][240], float A[240][200], float B[240][200]) {

    int k;
    int j;
    int i;
    for ( i = 0; i < 240; i++) {
        for ( j = 0; j < i + 1; j++) {
            C[i][j] *= beta;
        }
    }
    for ( i = 0; i < 240; i++) {
        for ( k = 0; k < 200; k++) {
            for ( j = 0; j < i + 1; j++) {
                C[i][j] += A[j][k] * alpha * B[i][k] + B[j][k] * alpha * A[i][k];
            }
        }
    }
}
