#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<float,16> float16;
typedef hls::vector<float,8> float8;
typedef hls::vector<float,4> float4;
typedef hls::vector<float,2> float2;
typedef hls::vector<float,1> float1;



void kernel_nlp(float A[200][200], float B[200][240], float B2[200][240]) {

    int k;
    int i;
    int j;
    for ( i = 0; i < 200; i++) {
        for ( j = 0; j < 240; j++) {
            for ( k = i + 1; k < 200; k++) {
                B[i][j] += A[k][i] * B2[k][j];
            }
        }
    }
    for ( i = 0; i < 200; i++) {
        for ( j = 0; j < 240; j++) {
            B[i][j] = alpha * B[i][j];
        }
    }
}
