#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<float,16> float16;
typedef hls::vector<float,8> float8;
typedef hls::vector<float,4> float4;
typedef hls::vector<float,2> float2;
typedef hls::vector<float,1> float1;



void kernel_nlp(float input[256][228][228], float weight[256][256][5][5], float output[256][224][224]) {

    int h;
    int q;
    int w;
    int p;
    int j;
    int i;
    for ( i = 0; i < 256; i++) {
        for ( j = 0; j < 256; j++) {
            for ( p = 0; p < 5; p++) {
                for ( q = 0; q < 5; q++) {
                    for ( h = 0; h < 224; h++) {
                        for ( w = 0; w < 224; w++) {
                            output[i][h][w] += weight[i][j][p][q] * input[j][h + p][w + q];
                        }
                    }
                }
            }
        }
    }
}
