#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<float,16> float16;
typedef hls::vector<float,8> float8;
typedef hls::vector<float,4> float4;
typedef hls::vector<float,2> float2;
typedef hls::vector<float,1> float1;



void kernel_nlp(float A[390][410], float x[410], float y[410], float tmp[390]) {

    int i;
    int j;
    for ( j = 0; j < 410; j++) {
        y[j] = 0.0;
    }
    for ( i = 0; i < 390; i++) {
        tmp[i] = 0.0;
    }
    for ( i = 0; i < 390; i++) {
        for ( j = 0; j < 410; j++) {
            tmp[i] = tmp[i] + A[i][j] * x[j];
        }
    }
    for ( j = 0; j < 410; j++) {
        for ( i = 0; i < 390; i++) {
            y[j] = y[j] + A[i][j] * tmp[i];
        }
    }
}
