catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project kernel_gemm
set_top kernel_gemm
# v++ -g, -D, -I, --advanced.prop kernel.kernel_gemm.kernel_flags
add_files "/home/spouget/iccad_24/autodse_without_tree_reduction/bert_100_768/_done/work_dir/output/fast/0/.merlin_prj/run/implement/exec/hls/__merlinkernel_kernel_gemm.c" -cflags " -D XILINX -I /home/spouget/iccad_24/autodse_without_tree_reduction/bert_100_768/_done/work_dir/output/fast/0/.merlin_prj/run/implement/exec/hls"
open_solution -flow_target vitis solution
set_part xcu200-fsgd2104-2-e
# v++ --hls.clock or --kernel_frequency
create_clock -period 250MHz -name default
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ --advanced.param compiler.deadlockDetection
config_rtl -deadlock_detection sim
# v++ --advanced.param compiler.axiDeadLockFree
config_interface -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format xo -ipname kernel_gemm
# v++ --hls.pre_tcl or --advanced.prop solution.hls_pre_tcl
source "/home/spouget/iccad_24/autodse_without_tree_reduction/bert_100_768/_done/work_dir/output/fast/0/.merlin_prj/run/implement/exec/hls/my_hls_pre.tcl"
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
