#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<float,16> float16;
typedef hls::vector<float,8> float8;
typedef hls::vector<float,4> float4;
typedef hls::vector<float,2> float2;
typedef hls::vector<float,1> float1;



void kernel_nlp(float x1[400], float x2[400], float y_1[400], float y_2[400], float A[400][400]) {

    int i;
    int j;
    for ( i = 0; i < 400; i++) {
        for ( j = 0; j < 400; j++) {
            x1[i] = x1[i] + A[i][j] * y_1[j];
        }
    }
    for ( i = 0; i < 400; i++) {
        for ( j = 0; j < 400; j++) {
            x2[i] = x2[i] + A[j][i] * y_2[j];
        }
    }
}
