#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<float,16> float16;
typedef hls::vector<float,8> float8;
typedef hls::vector<float,4> float4;
typedef hls::vector<float,2> float2;
typedef hls::vector<float,1> float1;



void kernel_nlp(float A[50][40][60], float C4[60][60], float sum[50][40][60]) {

    int r;
    int s;
    int p;
    int q;
    for ( r = 0; r < 50; r++) {
        for ( q = 0; q < 40; q++) {
            for ( p = 0; p < 60; p++) {
                sum[r][q][p] = 0.0;
            }
        }
    }
    for ( r = 0; r < 50; r++) {
        for ( q = 0; q < 40; q++) {
            for ( p = 0; p < 60; p++) {
                for ( s = 0; s < 60; s++) {
                    sum[r][q][p] += A[r][q][s] * C4[s][p];
                }
            }
        }
    }
    for ( r = 0; r < 50; r++) {
        for ( q = 0; q < 40; q++) {
            for ( p = 0; p < 60; p++) {
                A[r][q][p] = sum[r][q][p];
            }
        }
    }
}
