#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<double,16> double16;
typedef hls::vector<double,8> double8;
typedef hls::vector<double,4> double4;
typedef hls::vector<double,2> double2;
typedef hls::vector<double,1> double1;



void kernel_nlp(double A[400][400], double u1[400], double e1[400], double u2[400], double e2[400], double w[400], double x[400], double y[400], double z[400]) {

    int j;
    int i;
    for ( i = 0; i < 400; i++) {
        for ( j = 0; j < 400; j++) {
            A[i][j] = A[i][j] + u1[i] * e1[j] + u2[i] * e2[j];
        }
    }
    for ( i = 0; i < 400; i++) {
        for ( j = 0; j < 400; j++) {
            x[i] = x[i] + beta * A[j][i] * y[j];
        }
    }
    for ( i = 0; i < 400; i++) {
        x[i] = x[i] + z[i];
    }
    for ( i = 0; i < 400; i++) {
        for ( j = 0; j < 400; j++) {
            w[i] = w[i] + alpha * A[i][j] * x[j];
        }
    }
}
