#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<double,16> double16;
typedef hls::vector<double,8> double8;
typedef hls::vector<double,4> double4;
typedef hls::vector<double,2> double2;
typedef hls::vector<double,1> double1;



void kernel_nlp(double x1[400], double x2[400], double y_1[400], double y_2[400], double A[400][400]) {

    int i;
    int j;
    for ( i = 0; i < 400; i++) {
        for ( j = 0; j < 400; j++) {
            x1[i] = x1[i] + A[i][j] * y_1[j];
        }
    }
    for ( i = 0; i < 400; i++) {
        for ( j = 0; j < 400; j++) {
            x2[i] = x2[i] + A[j][i] * y_2[j];
        }
    }
}
