catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project kernel_bicg
set_top kernel_bicg
# v++ -g, -D, -I, --advanced.prop kernel.kernel_bicg.kernel_flags
add_files "/workspaces/bitbit/autodse/bicg/.merlin_prj/run/implement/exec/hls/__merlinkernel_kernel_bicg.c" -cflags " -D XILINX -I /workspaces/bitbit/autodse/bicg/.merlin_prj/run/implement/exec/hls -I /opt/polyopt/default/sources/polyopt-hls/hls_ap_test_suite/api"
open_solution -flow_target vitis solution
set_part xcu55c-fsvh2892-2L-e
# v++ --hls.clock or --kernel_frequency
create_clock -period 250MHz -name default
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ --advanced.param compiler.deadlockDetection
config_rtl -deadlock_detection sim
# v++ --advanced.param compiler.axiDeadLockFree
config_interface -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format xo -ipname kernel_bicg
# v++ --hls.pre_tcl or --advanced.prop solution.hls_pre_tcl
source "/workspaces/bitbit/autodse/bicg/.merlin_prj/run/implement/exec/hls/my_hls_pre.tcl"
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
