#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<float,16> float16;
typedef hls::vector<float,8> float8;
typedef hls::vector<float,4> float4;
typedef hls::vector<float,2> float2;
typedef hls::vector<float,1> float1;



void kernel_nlp(float A[250][250], float B[250][250], float tmp[250], float x[250], float y[250]) {

    int i;
    int j;
    for ( i = 0; i < 250; i++) {
        tmp[i] = 0.0;
    }
    for ( i = 0; i < 250; i++) {
        y[i] = 0.0;
    }
    for ( i = 0; i < 250; i++) {
        for ( j = 0; j < 250; j++) {
            tmp[i] += A[i][j] * x[j];
        }
    }
    for ( i = 0; i < 250; i++) {
        for ( j = 0; j < 250; j++) {
            y[i] += B[i][j] * x[j];
        }
    }
    for ( i = 0; i < 250; i++) {
        y[i] = alpha * tmp[i] + beta * y[i];
    }
}
